# S5 — NumPy Examples

In [ ]:
import numpy as np  

In [ ]:
a = np.array([1, 2, 3])  
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[1 2 3]
(3,)
1
3
int64


In [3]:
print(np.zeros((2, 3)))  # Create zeros
print(np.ones((2, 3)))     # Create ones
print(np.full((2, 3), 7))  # Fill with a value

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


In [4]:
print(np.arange(0, 10, 2))     # Use a fixed step
print(np.linspace(0, 10, 5))    # Use a fixed number of values
print(np.eye(3))                 # Create an identity matrix

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a = np.array([1, 2, 3], dtype=np.int32)  # Set dtype
b = a.astype(np.float64)                    # Convert dtype

print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1 2 3]
int32
[1. 2. 3.]
float64


In [6]:
a = np.arange(10)

print(a[2:6])    # Slice values
print(a[1:8:2])  # Slice with a step
print(a[::-1])   # Reverse the array

[2 3 4 5]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [7]:
A = np.arange(12).reshape(3, 4)

print(A)
print(A[1, 2])      # Select one element
print(A[1, :])      # Select one row
print(A[:, 1])      # Select one column
print(A[0:2, 1:3])  # Select a submatrix

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[1 5 9]
[[1 2]
 [5 6]]


In [8]:
a = np.array([10, 20, 30, 40])
part = a[1:3]  # Create a view
part[0] = 999

print(part)
print(a)

[999  30]
[ 10 999  30  40]


In [9]:
a = np.array([10, 20, 30, 40])
part = a[1:3].copy()  # Create an independent copy
part[0] = 999

print(part)
print(a)

[999  30]
[10 20 30 40]


In [10]:
a = np.array([1, 5, 8, 2, 10])

print(a > 4)      # Create a Boolean mask
print(a[a > 4])   # Select matching values

[False  True  True False  True]
[ 5  8 10]


In [11]:
a = np.arange(10)

print(a[(a >= 3) & (a <= 7)])  # Combine conditions with AND
print(a[(a < 3) | (a > 7)])    # Combine conditions with OR
print(a[~(a % 2 == 0)])         # Negate a condition

[3 4 5 6 7]
[0 1 2 8 9]
[1 3 5 7 9]


In [12]:
a = np.arange(10)
a[a % 2 == 0] = -1  # Replace matching values

print(a)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [13]:
a = np.array([10, 20, 30, 40, 50])

print(a[[0, 2, 4]])  # Fancy indexing
print(a[[3, 3, 0]])  # Repeat indices

[10 30 50]
[40 40 10]


In [14]:
A = np.arange(12).reshape(3, 4)

print(A[[0, 2], [1, 3]])  # Select paired coordinates

rows = [0, 2]
cols = [1, 3]
print(A[np.ix_(rows, cols)])  # Select all row-column combinations

[ 1 11]
[[ 1  3]
 [ 9 11]]


In [15]:
A = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [3, 30, 300],
    [4, 40, 400]
])

mask = A[:, 0] > 2
print(A[mask, 1:3])  # Combine masking and slicing

[[ 30 300]
 [ 40 400]]


In [16]:
a = np.arange(12)

print(a.reshape(3, 4))   # Reshape into 3 rows
print(a.reshape(2, 2, 3))
print(a.reshape(3, -1))  # Infer one dimension

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

r = A.ravel()      # Return a view when possible
f = A.flatten()    # Return a copy

r[0] = 99
f[1] = 88

print(A)
print(r)
print(f)

[[99  2  3]
 [ 4  5  6]]
[99  2  3  4  5  6]
[ 1 88  3  4  5  6]


In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)        # Transpose the matrix
print(A.shape)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)


In [19]:
a = np.array([1, 2, 3])

print(a.T.shape)            # 1D transpose does not change shape
print(a.reshape(1, -1))     # Create a row vector
print(a.reshape(-1, 1))     # Create a column vector

(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]


In [20]:
a = np.array([1, 2, 3])

print(a + 10)   # Add a scalar
print(a * 2)    # Multiply by a scalar
print(a ** 2)   # Square each value
print(a > 1)    # Compare each value

[11 12 13]
[2 4 6]
[1 4 9]
[False  True  True]


In [21]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A * B)  # Element-wise multiplication
print(A @ B)  # Matrix multiplication

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [22]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.min())
print(A.max())
print(A.sum())
print(A.mean())
print(A.sum(axis=0))  # Reduce rows
print(A.sum(axis=1))  # Reduce columns

1
6
21
3.5
[5 7 9]
[ 6 15]


## Extra tools used in the first 30 exercises

In [23]:
a = np.array([5, 0, 8, 0, 2])

print(np.nonzero(a)[0])  # Get non-zero indices

[0 2 4]


In [24]:
rng = np.random.default_rng(42)

print(rng.random(5))                    # Random floats
print(rng.integers(0, 10, size=(2, 3)))  # Random integers

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[[5 9 7]
 [7 7 7]]


In [25]:
A = np.ones((3, 3))

print(np.pad(A, 1, mode="constant", constant_values=0))  # Add a border

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
values = np.array([4, 5, 6])

print(np.diag(values))       # Main diagonal
print(np.diag(values, k=-1)) # Lower diagonal

[[4 0 0]
 [0 5 0]
 [0 0 6]]
[[0 0 0 0]
 [4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]]


In [27]:
pattern = np.array([
    [0, 1],
    [1, 0]
])

print(np.tile(pattern, (2, 3)))  # Repeat a pattern

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [28]:
print(np.unravel_index(7, (3, 4)))  # Convert a flat index to coordinates

(np.int64(1), np.int64(3))


In [29]:
a = np.array([10, 20, 30, 40], dtype=float)

normalized = (a - a.min()) / (a.max() - a.min())  # Min-max normalization
print(normalized)

[0.         0.33333333 0.66666667 1.        ]


In [30]:
pixel_dtype = np.dtype([
    ("r", np.uint8),
    ("g", np.uint8),
    ("b", np.uint8)
])

pixels = np.array([
    (255, 0, 0),
    (0, 255, 0),
    (0, 0, 255)
], dtype=pixel_dtype)

print(pixels)
print(pixels["r"])  # Access one field

[(255,   0,   0) (  0, 255,   0) (  0,   0, 255)]
[255   0   0]


In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.intersect1d(a, b))  # Find common values

[3 4]


In [32]:
a = np.array([-2.7, 2.7])

print(np.floor(a))  # Round down
print(np.ceil(a))   # Round up
print(np.trunc(a))  # Remove decimals

[-3.  2.]
[-2.  3.]
[-2.  2.]


In [33]:
a = np.array([1.0, np.nan, np.inf])

print(np.isnan(a))  # Detect NaN
print(np.isinf(a))  # Detect infinity
print(0.1 + 0.2 == 0.3)
print(np.isclose(0.1 + 0.2, 0.3))  # Compare floats safely

[False  True False]
[False False  True]
False
True
