# S6 — Broadcasting, Axis and NumPy Linear Algebra

In [1]:
import numpy as np  # Import NumPy

## Broadcasting

In [2]:
A = np.array([[10], [20], [30]])  # Shape: (3, 1)
B = np.array([[1, 2, 3, 4]])        # Shape: (1, 4)

result = A + B  # Broadcast to shape (3, 4)

print(A.shape, B.shape, result.shape)
print(result)

(3, 1) (1, 4) (3, 4)
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [3]:
A = np.zeros((5, 3))
row_values = np.array([10, 20, 30])
column_values = np.array([10, 20, 30, 40, 50])[:, None]

print(A + row_values)     # Apply values to each row
print(A + column_values)  # Apply one value to each row

[[10. 20. 30.]
 [10. 20. 30.]
 [10. 20. 30.]
 [10. 20. 30.]
 [10. 20. 30.]]
[[10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]
 [40. 40. 40.]
 [50. 50. 50.]]


In [4]:
x = np.arange(4)

print(x.shape)
print(x[:, None].shape)
print(x[None, :].shape)
print(x[:, None] + x[None, :])  # Outer sum

(4,)
(4, 1)
(1, 4)
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [5]:
A = np.arange(8).reshape(2, 1, 4)
B = np.array([[10], [20], [30]])

result = A + B  # Interpret B as shape (1, 3, 1)

print(A.shape, B.shape, result.shape)
print(result)

(2, 1, 4) (3, 1) (2, 3, 4)
[[[10 11 12 13]
  [20 21 22 23]
  [30 31 32 33]]

 [[14 15 16 17]
  [24 25 26 27]
  [34 35 36 37]]]


## Axis and keepdims

In [6]:
X = np.array([
    [1, 2, 3],
    [10, 20, 30]
])

print(X.mean())
print(X.mean(axis=0))
print(X.mean(axis=1))
print(X.mean(axis=-1))

11.0
[ 5.5 11.  16.5]
[ 2. 20.]
[ 2. 20.]


In [7]:
row_means = X.mean(axis=1, keepdims=True)
row_std = X.std(axis=1, keepdims=True)
standardized = (X - row_means) / row_std

print(row_means)
print(row_means.shape)
print(X - row_means)
print(standardized)
print(standardized.mean(axis=1))
print(standardized.std(axis=1))

[[ 2.]
 [20.]]
(2, 1)
[[ -1.   0.   1.]
 [-10.   0.  10.]]
[[-1.22474487  0.          1.22474487]
 [-1.22474487  0.          1.22474487]]
[0. 0.]
[1. 1.]


In [8]:
A = np.zeros((2, 3, 4))

print(A.mean(axis=0).shape)
print(A.mean(axis=1).shape)
print(A.mean(axis=2).shape)
print(A.mean(axis=-1).shape)
print(A.mean(axis=1, keepdims=True).shape)

(3, 4)
(2, 4)
(2, 3)
(2, 3)
(2, 1, 4)


In [9]:
A = np.arange(24).reshape(2, 3, 4)

print(A.sum(axis=(1, 2)))
print(A.sum(axis=(1, 2)).shape)
print(A.sum(axis=(1, 2), keepdims=True))
print(A.sum(axis=(1, 2), keepdims=True).shape)

[ 66 210]
(2,)
[[[ 66]]

 [[210]]]
(2, 1, 1)


In [10]:
A = np.array([
    [5, 2, 8],
    [1, 9, 4]
])

print(A.max(axis=0))
print(A.max(axis=1))
print(A.argmin(axis=0))
print(A.argmax(axis=1))
print(A.argmax(axis=1, keepdims=True))

[5 9 8]
[8 9]
[1 0 1]
[2 1]
[[2]
 [1]]


## np.linalg.norm

In [11]:
v = np.array([3.0, 4.0])

print(np.linalg.norm(v))
print(v / np.linalg.norm(v))

5.0
[0.6 0.8]


In [12]:
X = np.array([
    [3.0, 4.0],
    [5.0, 12.0]
])

row_norms = np.linalg.norm(X, axis=1, keepdims=True)
normalized = X / row_norms

print(row_norms)
print(normalized)
print(np.linalg.norm(normalized, axis=1))

[[ 5.]
 [13.]]
[[0.6        0.8       ]
 [0.38461538 0.92307692]]
[1. 1.]


In [13]:
X = np.array([
    [0.0, 0.0],
    [3.0, 4.0]
])

norms = np.linalg.norm(X, axis=1, keepdims=True)
safe_norms = np.where(norms == 0, 1, norms)

print(X / safe_norms)

[[0.  0. ]
 [0.6 0.8]]


## solve and inv

In [14]:
A = np.array([
    [2.0, 1.0],
    [1.0, 3.0]
])
b = np.array([5.0, 6.0])

x = np.linalg.solve(A, b)

print(x)
print(A @ x)
print(np.allclose(A @ x, b))

[1.8 1.4]
[5. 6.]
True


In [15]:
A_inverse = np.linalg.inv(A)

print(A_inverse)
print(A @ A_inverse)
print(np.allclose(x, A_inverse @ b))

[[ 0.6 -0.2]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
True


In [16]:
B = np.array([
    [5.0, 1.0],
    [6.0, 0.0]
])

X = np.linalg.solve(A, B)

print(X)
print(np.allclose(A @ X, B))

[[ 1.8  0.6]
 [ 1.4 -0.2]]
True


## matrix_rank and det

In [17]:
full_rank = np.array([
    [1.0, 2.0],
    [3.0, 4.0]
])

rank_deficient = np.array([
    [1.0, 2.0],
    [2.0, 4.0]
])

print(np.linalg.matrix_rank(full_rank))
print(np.linalg.matrix_rank(rank_deficient))
print(np.linalg.det(full_rank))
print(np.linalg.det(rank_deficient))

2
1
-2.0000000000000004
0.0


In [18]:
matrices = np.array([
    [[1.0, 0.0], [0.0, 1.0]],
    [[1.0, 2.0], [2.0, 4.0]]
])

print(np.linalg.matrix_rank(matrices))
print(np.linalg.det(matrices))

[2 1]
[1. 0.]


## eig and eigh

In [19]:
A = np.array([
    [4.0, 1.0],
    [2.0, 3.0]
])

eigenvalues, V = np.linalg.eig(A)
Lambda = np.diag(eigenvalues)

print(eigenvalues)
print(V)
print(np.allclose(A @ V, V @ Lambda))

[5. 2.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
True


In [20]:
A_reconstructed = V @ Lambda @ np.linalg.inv(V)

print(A_reconstructed)
print(np.allclose(A, A_reconstructed))

[[4. 1.]
 [2. 3.]]
True


In [21]:
S = np.array([
    [2.0, 1.0],
    [1.0, 3.0]
])

eigenvalues, Q = np.linalg.eigh(S)
Lambda = np.diag(eigenvalues)

print(eigenvalues)
print(Q.T @ Q)
print(np.allclose(S, Q @ Lambda @ Q.T))

[1.38196601 3.61803399]
[[ 1.0000000e+00 -1.2127222e-17]
 [-1.2127222e-17  1.0000000e+00]]
True


## lstsq

In [22]:
A = np.array([
    [1.0, 1.0],
    [1.0, 2.0],
    [1.0, 3.0]
])
b = np.array([1.0, 2.0, 2.0])

x, residuals, rank, singular_values = np.linalg.lstsq(A, b, rcond=None)

print(x)
print(A @ x)
print(b - A @ x)
print(rank)
print(singular_values)

[0.66666667 0.5       ]
[1.16666667 1.66666667 2.16666667]
[-0.16666667  0.33333333 -0.16666667]
2
[4.07914333 0.60049122]


## Quick Reference

```python
a[:, None]
a[None, :]

A.mean(axis=0)
A.mean(axis=-1)
A.std(axis=1, keepdims=True)
A.sum(axis=(1, 2), keepdims=True)
A.argmin(axis=0)
A.argmax(axis=1)

np.linalg.norm(v)
np.linalg.solve(A, b)
np.linalg.inv(A)
np.linalg.matrix_rank(A)
np.linalg.det(A)
np.linalg.eig(A)
np.linalg.eigh(A)
np.linalg.lstsq(A, b, rcond=None)
```
